/* This file is autogenerated, DO NOT MODIFY */
package main

type Statement interface {
	Accept(visitor StatementVisitor) error
}

type ExpressionStatement struct {
	Expression Expression
}

func (e *ExpressionStatement) Accept(visitor StatementVisitor) error {
	return visitor.VisitExpressionStatement(e)
}

type PrintStatement struct {
	Expression Expression
}

func (e *PrintStatement) Accept(visitor StatementVisitor) error {
	return visitor.VisitPrintStatement(e)
}

type VarStatement struct {
	Name        *Token
	Initializer Expression
}

func (e *VarStatement) Accept(visitor StatementVisitor) error {
	return visitor.VisitVarStatement(e)
}

type BlockStatement struct {
	Statements []Statement
}

func (e *BlockStatement) Accept(visitor StatementVisitor) error {
	return visitor.VisitBlockStatement(e)
}

type StatementVisitor interface {
	VisitExpressionStatement(statement *ExpressionStatement) error
	VisitPrintStatement(statement *PrintStatement) error
	VisitVarStatement(statement *VarStatement) error
	VisitBlockStatement(statement *BlockStatement) error
}
