/* This file is autogenerated, DO NOT MODIFY */
package main

type Statement interface {
	Accept(visitor StatementVisitor) error
}

type ExpressionStatement struct {
	Expression Expression
}

func (e *ExpressionStatement) Accept(visitor StatementVisitor) error {
	return visitor.VisitExpressionStatement(e)
}

type PrintStatement struct {
	Expression Expression
}

func (e *PrintStatement) Accept(visitor StatementVisitor) error {
	return visitor.VisitPrintStatement(e)
}

type StatementVisitor interface {
	VisitExpressionStatement(statement *ExpressionStatement) error
	VisitPrintStatement(statement *PrintStatement) error
}
